version: '3'

services:
  timecoder:
    build: ../
    restart: always
    ports:
      - 8081:8080
    networks:
      - api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - USER_NAME=root
      - PASSWORD=admin
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=timecoder
    volumes:
    - "./mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
    networks:
      - api
networks:
  api: